// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npwxjtirtihgfomcnfdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wd3hqdGlydGloZ2ZvbWNuZmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2OTE4NzEsImV4cCI6MjA1NjI2Nzg3MX0.USiCZsfXgSaXWVwM6eoM8VxewPFFsyD1rxaHunU5N8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);